name: Telegram Notify

on:
  workflow_run:
    workflows: ["Preprocess PR"]
    types:
      - completed

jobs:
  download-artifacts:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: "Download artifact"
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));

      - name: Unzip artifact
        run: unzip pr.zip

      - name: "Comment on PR"
        run: |
          export PR_NUMBER=$(cat ./NR)
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Send telegram notification on PR
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_DEST_CHAT }}
          token: ${{ secrets.TELEGRAM_ACCESS_TOKEN }}
          disable_notification: true
          message: |
            ${{ github.actor }} raised a PR.
            Repository: ${{ github.repository }}

            All members can review here:
            https://github.com/${{ github.repository }}/pull/${{ env.PR_NUMBER }}
